# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminal_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.table_menu = QtWidgets.QTableWidget(self.centralwidget)
        self.table_menu.setObjectName("table_menu")
        self.table_menu.setColumnCount(0)
        self.table_menu.setRowCount(0)
        self.gridLayout.addWidget(self.table_menu, 1, 0, 5, 1)
        self.add_dish_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_dish_btn.setObjectName("add_dish_btn")
        self.gridLayout.addWidget(self.add_dish_btn, 1, 1, 1, 1)
        self.ingredients_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ingredients_btn.setObjectName("ingredients_btn")
        self.gridLayout.addWidget(self.ingredients_btn, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.table_order = QtWidgets.QTableWidget(self.centralwidget)
        self.table_order.setObjectName("table_order")
        self.table_order.setColumnCount(0)
        self.table_order.setRowCount(0)
        self.gridLayout.addWidget(self.table_order, 4, 1, 1, 1)
        self.del_dish_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_dish_btn.setObjectName("del_dish_btn")
        self.gridLayout.addWidget(self.del_dish_btn, 5, 1, 1, 1)
        self.total_price_label = QtWidgets.QLabel(self.centralwidget)
        self.total_price_label.setObjectName("total_price_label")
        self.gridLayout.addWidget(self.total_price_label, 6, 0, 1, 1)
        self.pay_order_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pay_order_btn.setObjectName("pay_order_btn")
        self.gridLayout.addWidget(self.pay_order_btn, 6, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.about_btn = QtWidgets.QAction(MainWindow)
        self.about_btn.setObjectName("about_btn")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Наше меню:"))
        self.add_dish_btn.setText(_translate("MainWindow", "Добавить в заказ"))
        self.ingredients_btn.setText(_translate("MainWindow", "Посмотреть ингредиенты"))
        self.label.setText(_translate("MainWindow", "Ваш заказ:"))
        self.del_dish_btn.setText(_translate("MainWindow", "Удалить блюдо"))
        self.total_price_label.setText(_translate("MainWindow", "Итого: 0р"))
        self.pay_order_btn.setText(_translate("MainWindow", "Оплатить заказ"))
        self.about_btn.setText(_translate("MainWindow", "О программе"))
